http_port 3128
visible_hostname squid-template

acl authenticated proxy_auth REQUIRED
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm Private proxy
auth_param basic credentialsttl 2 hours

http_access allow authenticated
http_access deny all

cache deny all
forwarded_for delete
via off
request_header_access X-Forwarded-For deny all
