#!/bin/sh
set -eu

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE USER ${DIODE_POSTGRES_USER} WITH PASSWORD '${DIODE_POSTGRES_PASSWORD}';
CREATE DATABASE ${DIODE_POSTGRES_DB_NAME} OWNER ${DIODE_POSTGRES_USER};
CREATE USER ${HYDRA_POSTGRES_USER} WITH PASSWORD '${HYDRA_POSTGRES_PASSWORD}';
CREATE DATABASE ${HYDRA_POSTGRES_DB_NAME} OWNER ${HYDRA_POSTGRES_USER};
EOSQL
